### ISSUE TITLE
Under the competition version, two agent use a single network or use two different networks?

### ISSUE THREAD

**Issue by mingzibuhaoqi** [DrZomgwtfbbq/DeepMind-Atari-Deep-Q-Learner-2Player#3]
Feel confuse
Train a single q-network, this network is shared between two agents?
Or, train two q-network, each agent occupy a q-network, and train two networks?
Thanks for any answer

**Comment by tambetm** [comment]
This implementation trains two separate networks, because they need different inputs - in one case the player is on left side of screen, in other case the player is on the right side of screen.

**Comment by mingzibuhaoqi** [comment]
Thank you so much
Do you think...using only one network for two agents can work too? and... be simpler?
The 'left and right' problem may be solved by rotating the screen.

**Comment by DorianKodelja** [comment]
The goal of this implementation is to specifically allow a multiagent paradigm, ie two agents dynamically learning their own policy based on one another.
It is indeed possible to train one network to control both paddles but then it's only one agent learning  to juggle with two paddles.
